$(document).ready(function(){
    $(".owl-carousel").owlCarousel({
        loop:true,
        margin:10,
        responsiveClass:true,
        autoplay:true, 
        rewind:true,
        autoplayTimeout:3000, 
        autoplaySpeed: 2000, //Hace que las imagenes se cambien mas despacio
        responsive:{
            0:{
                items:1,
                nav:true
            },
            600:{
                items:3,
                nav:false
            },
            1000:{
                items:5,
                nav:true,
                loop:false
            }
        }
    });
});